### PR TITLE
Remove old discovery registers

### PR DESCRIPTION
**Pull request by danmitchell-**
No longer needed or promoted have been promoted up.

cc @elliecraven

### CODE REVIEW

**Comment by elliecraven** [comment]
@danmitchell- looks fine to me to remove all of these, but worth checking with @nacnudus whether any of the meat ones need to stay for us to pick up later, or if we're starting from scratch with those?

**Comment by nacnudus** [comment]
@elliecraven Dan already did :) I think they can be deleted because they'll probably be replaced by more-general 'food' registers, which all follow the same structure.

**Comment by michaelabenyohai** [comment]
Why are we removing street-custodian when it is linked to from street and address @danmitchell- @nacnudus ?

**Comment by michaelabenyohai** [comment]
We also need a corresponding PR for the change in the `deployment` repository. If we merge this the register endpoints will still exist but we'll simply get a PaaS error returned.

**Comment by nacnudus** [comment]
`street` and `address` can also be deleted @danmitchell- @michaelabenyohai from my point of view.

**Comment by danmitchell-** [comment]
I've left `street-custodian` as it links with `street` and `address`. We can remove them all separately if we wish.

**Comment by michaelabenyohai** [comment]
I have just noticed that `place` shouldn't be removed because it is linked to from `street`.

**Comment by danmitchell-** [comment]
Also put `place` back on this one. Please approve and i'll merge

**Pull request merged**
