### PR TITLE
Add alpha phase into header

### PR DESCRIPTION
**Pull request by dankmitchell**
### Context
We need to tell our users that GOV.UK Registers as a service is in Aplha

### Changes proposed in this pull request
- Add `Alpha` phase tag to header
- Remove the register name
- Remove navigation

### Guidance to review
View any html page

### CODE REVIEW

**Comment by michaelabenyohai** [comment]
This means that unless we are on the front page there's no way of knowing what register you're looking at unless you look at the URL. Are we ok with that?

**Comment by dankmitchell** [comment]
It's still on the page i.e. https://country.register.gov.uk/records

**Comment by michaelabenyohai** [comment]
@dankmitchell that only exists for non-beta registers e.g. https://school-eng.alpha.openregister.org/records doesn't have it

**Comment by dankmitchell** [comment]
Ah okay. Personally, I'm fine with this since its only the older `beta` registers that users know have a HTML view. We wouldn't be sending users to the API inspector and it's not part of the journey, especially the non-homepage view. Deffo a question for @conordelahunty

**Pull request merged**
