### PR TITLE
Papercuts

### PR DESCRIPTION
**Pull request by symroe**
Couple of easy fixes. Not sure about the vars in 423bab0 – see the comment on that commit for more. Happy to fixup the commit with the correct variables and words if need be.

### CODE REVIEW

**Comment by philandstuff** [comment]
I spoke to @symroe IRL about this. The `table-cell` trick doesn't seem to quite fix the comma whitespace issue, and the "view this register" link needs to, at least, be configurable so it doesn't appear on registers other than the register register.

We can talk further about next steps.

**Comment by michaelabenyohai** [comment]
https://github.com/openregister/openregister-java/pull/108 addresses the "view this register" link and configures it only for the register register.

**Comment by michaelabenyohai** [comment]
Moved table-cell trick to its won branch - turns out chrome was caching CSS and it does work locally for me now. New PR at https://github.com/openregister/openregister-java/pull/111.

**Comment by philandstuff** [comment]
Going to close as I think we've dealt with the issues in this PR. @symroe please reopen if there are still things we haven't addressed.

**Pull request closed without merging**
