### PR TITLE
Make deploys zero-downtime

### PR DESCRIPTION
**Pull request by samcrang**
We lean on the `cf-blue-green-deploy`[1] to make this as easy as
possible.

[1] https://github.com/bluemixgaragelondon/cf-blue-green-deploy

### CODE REVIEW

**Comment by karlbaker02** [comment]
With our current deployment in CodeDeploy we deploy to one instance at a time, and wait for the `validate.sh` script to complete before moving on to the next deploy. Do we still do this with PaaS? Regarding the blue-green plugin, we're not passing any tests to run so the only reason we're using it is to automate the process of deploying, swapping out the old for the new and cleaning the old?

**Comment by samcrang** [comment]
On `validate.sh`: the `manifest.yaml` specifies a `healthcheck: /records`—I'd expect this to cause the deploy to fail and drop out but I still need to verify what actually happens.

And yes, the blue-green plugin [eliminates the need to do something like this](https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html).

And you're right we have no smoke tests at the moment—we should probably create some.

**Comment by samcrang** [comment]
@karlbaker02 I've run through a couple of failure scenarios and discovered the health check wasn't actually working—I've fixed that in the manifest and failed deploys work like you'd expect (ie. the deploy stops, is deteceted as a failure and the original app still recieves all the traffic).

**Comment by karlbaker02** [comment]
Discussed above issues with Sam.

**Pull request merged**
